name: Format check

on: [push, pull_request]

jobs:
 check:
  name: Format check
  runs-on: ubuntu-latest
  steps:
   - name: ðŸ§± Clone repository
     uses: actions/checkout@v4
   - name: ðŸ”© Install Deno
     uses: denoland/setup-deno@v2
     with:
      deno-version: v2.x
   - name: ðŸš€ Check formatting
     run: deno fmt --check
