name: Types Check

on: [push, pull_request]

jobs:
  check:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ§± Clone repository
        uses: actions/checkout@v3
      - name: ðŸ”© Install Deno 
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: ðŸš€ Check types
        run: deno check main.ts